Add tree-editor example
eclipsesource/generator-theia-extension pull request #16
Opened 2020-05-15 11:32 UTC by TheZoker

This PR adds the tree-editor example based on the [Theia Tree Editor](https://github.com/eclipsesource/theia-tree-editor)

2020-05-15 13:02 UTC, lucas-koehler requested changes
Besides the comments in the code, I wonder about the license of the templates and the generated code. IMO, it doesn't make too much sense to generate code with an EclipseSource copyright header.
@sdirix what do you think?

2020-05-15 13:02 UTC, lucas-koehler commented on templates/tree-editor/tree-contribution.ts
> +
We don't need this, I'd remove this and simply add a comment:
```typescript
// register your custom commands here
```

2020-05-15 13:02 UTC, lucas-koehler commented on templates/tree-editor/tree-frontend-module.ts
> +  // bind to themselves because we use it outside of the editor widget, too.
```suggestion
  // bind to themselves because we use them outside of the editor widget, too.
```

2020-05-15 13:02 UTC, lucas-koehler commented on templates/tree-editor/tree/tree-container.ts
> +/*!
We don't need the tree-container for this simple example because we don't need to register a command. I think even for the coffee example we won't need it because there won't be integration with GLSP in this example. Consequently, this file can be deleted completely.

2020-05-15 13:02 UTC, lucas-koehler commented on templates/tree-editor/tree/tree-editor-widget.ts
> +  }
I think we can delete these methods because they don't need to be overridden for simple resource editors.

2020-05-15 13:02 UTC, lucas-koehler commented on templates/tree-editor/tree/tree-node-factory.ts
> +        type: data.$id,
This seems incorrect, don't we use `typeId` as our id field?

2020-05-15 13:14 UTC, lucas-koehler commented
@TheZoker I had a talk with @sdirix . Please remove all copyright headers in the template for now. We will clarify at a later point if we re-add some and if yes which ones.

2020-05-15 13:30 UTC, TheZoker commented
@lucas-koehler Thanks for the feedback! I addressed all comments in the latest commit

2020-05-15 13:56 UTC, lucas-koehler commented
Thanks! I tried to test it locally by calling `npm link` on the root level of this repository to register a locally built version for my npm. Then I called `yo theia-extension`. I can select the tree editor and specify a name but then the generation fails:
```
? The extension's type TreeEditor
? The extension's name Bert
Bert
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Could not find matching close tag for "<%=".
    at /home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:710:19
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:695:15)
    at Template.compile (/home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:572:12)
    at Object.compile (/home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:215:18)
    at Object.exports.render (/home/lucas/Git/generator-theia-extension/node_modules/ejs/lib/ejs.js:419:10)
    at render (/home/lucas/Git/generator-theia-extension/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/home/lucas/Git/generator-theia-extension/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:34:16)
    at applyProcessingFunc (/home/lucas/Git/generator-theia-extension/node_modules/mem-fs-editor/lib/actions/copy.js:14:16)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/lucas/Git/generator-theia-extension/node_modules/yeoman-generator/lib/index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

2020-05-15 14:29 UTC, TheZoker commented
Note: The name should be lowercase 

Do the other examples work? Does it work, when you switch to the current master and try one of the existing examples?

2020-05-15 14:53 UTC, lucas-koehler commented
@TheZoker lower case doesn't make a difference, it actually always "fixes" it to be uppercase in the end. I tried generating the widget and the label provider examples and both worked fine.

2020-05-18 11:34 UTC, lucas-koehler approved these changes
I tested it again but cleaned all `node_modules` folders and similar things from the tree-editor template's folder. With this the generation worked fine. The generated code can be built and the generated Theia instance and tree editor seem to work fine :)

I guess some left-over artifacts tripped EJS before.

2020-05-18 11:40 UTC, lucas-koehler commented
@TheZoker I changed the base because I think it makes sense to merge into a separate branch instead of master. This separate branch can then later be used to open a PR against upstream

2020-05-18 11:45 UTC, merged